name: Build Android APK from Master branch
on:
  push:
    branches:
      - main
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run linter
        run: |
          npm run lint
      - name: Run tests
        run: |
          npm run test
          
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android APK
        run: |
          cd android && ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
          mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/mensatalk-dev.apk
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: mensatalk-dev.apk
          path: android/app/build/outputs/apk/release/
